services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: unitta
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./unitta-backend
    restart: always
    ports:
      - "3333:3333"  # Porta do servidor backend
      - "5555:5555"  # Porta do Prisma Studio
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/unitta
      http_proxy: ""
      https_proxy: ""
      NODE_EXTRA_CA_CERTS: /app/certs/nscacert_combined.crt
      NODE_TLS_REJECT_UNAUTHORIZED: 0 # Somente para DEV
    volumes:
      - ./unitta-backend:/app
    working_dir: /app
    command: npx ts-node-dev src/server.ts

  frontend:
    platform: linux/amd64
    build: ./unitta-frontend
    ports:
      - "5173:5173"
    volumes:
      - ./unitta-frontend:/app
      - /app/node_modules
    working_dir: /app
    command: pnpm run dev

volumes:
  postgres_data:
